### ISSUE TITLE
How to get all placemark coordinates from kml_data

### ISSUE THREAD

**Issue by Dynabits** [georust/kml#12]
Sorry if this question is too stupid, I'm very new and fresh to Rust and KML files.

I have this code from examples that parses a kml file:

```
// Read from a file path
let kml_path = Path::new("points_test.kml")
    .join("tests")
    .join("fixtures")
    .join("polygon.kml");
let mut kml_reader = KmlReader::<_, f64>::from_path(kml_path).unwrap();
let kml_data = kml_reader.read().unwrap();
```

Now how do I search for all placemarks inside "kml_data" and println! all their coordinates?

I'm not ashamed to say that I spent two hours trying to do that without any success, any example code that do it would be so appreciated.
Thank you.

**Comment by pjsier** [comment]
No problem! The base type `Kml` is an enum that can represent any element within a KML document, that way we can parse KML snippets as well as full documents. That means you can use `match` statements to recursively pull out all of the potential elements that can contain other elements and filter for `Placemark` elements alone.

```rust
fn flatten_kml(kml: Vec<Kml>) -> Vec<Kml> {
    kml.into_iter()
        .flat_map(|k| match k {
            Kml::KmlDocument(d) => flatten_kml(d.elements),
            Kml::Document { attrs: _, elements } => flatten_kml(elements),
            Kml::Folder { attrs: _, elements } => flatten_kml(elements),
            k => vec![k],
        })
        .collect()
}

let flat_kml = flatten_kml(vec![kml_data]);
flat_kml
    .into_iter()
    .filter_map(|k| match k {
        Kml::Placemark(p) => Some(p),
        _ => None,
    })
    .for_each(|placemark| {
        if let Some(Geometry::Point(p)) = placemark.geometry {
            println!("{},{}", p.coord.x, p.coord.y);
        }
    });
```

If you know you're only working with `Placemark` elements and you just want all of the geometries you can install the crate with the `geo-types` feature and use the `quick_collection` method and filter for points, [example in the README](https://github.com/georust/kml#conversion)

Let me know if that's helpful!

**Comment by Dynabits** [comment]
> Let me know if that's helpful!

That's very helpful, thank you for the explanation and example code, that's so kind of you.
I only had to remove these lines from "kml_path" variable:
```
    .join("tests")
    .join("fixtures")
    .join("polygon.kml")
```
Thank you again you saved me.

**Comment by pjsier** [comment]
Glad to hear it! Closing this
