### ISSUE TITLE
Add support for kml:Location

### ISSUE THREAD

**Issue by pjsier** [georust/kml#4]
This doesn't currently implement `kml:Location` ([10.10 in the spec](http://docs.opengeospatial.org/is/12-007r2/12-007r2.html#542)), but it should be straightforward to implement here.

This would involve creating a `Location` struct in a new `src/types/location.rs` file with properties similar to `Point`. This is different in that its coordinates are in separate `latitude` and `longitude` elements instead of a single comma-separated line like `Point`.

Once the type is created it can be added to the [`Kml` enum](https://github.com/georust/kml/blob/main/src/types/kml.rs#L56) and a setup for parsing it added to the reader and writer implementations.

It looks like this is mostly used inside of `kml:Model`, so this is mostly preparation for implementing that struct.

**Comment by Nadhum** [comment]
Hey, will take a shot at this.
