### ISSUE TITLE
Add "Geospatial" category to `Cargo.toml`

### ISSUE THREAD

**Issue by frewsxcv** [georust/kml#43]
https://github.com/rust-lang/crates.io/commit/9b65b4c004c503cf234c503e82d8575ba42c45e2

https://doc.rust-lang.org/cargo/reference/manifest.html#the-categories-field

**Comment by pjsier** [comment]
Thanks for the issue! Closed in https://github.com/georust/kml/commit/b53faee9c5c4a4b742ce7f693a580c9dc7ec0962
