### ISSUE TITLE
Panic when parsing a file containing invalid UTF-8

### ISSUE THREAD

**Issue by TilBlechschmidt** [georust/kml#44]
While it might be safe to assume that data passed to this library is valid UTF-8, there are circumstances where that might not be the case. In my particular use-case I am trying to guess which file format a file has and among the valid options is a compressed archive. This causes a panic due to the following line:
https://github.com/georust/kml/blob/b53faee9c5c4a4b742ce7f693a580c9dc7ec0962/src/reader.rs#L1001
In my opinion, this should be passed out to the user of the library instead of panicking. At the very least it should be an `.expect("...")` to give some context. Especially in cases of file corruption, this could be hit when parsing an otherwise valid KML — crashing the hosting application 😢

**Comment by TilBlechschmidt** [comment]
Let me know if you would be open to PRs, I could create a fix in a bit 🙂

**Comment by TilBlechschmidt** [comment]
I looked through the whole reader and it appears there are two more occurrences of a similar kind:
https://github.com/georust/kml/blob/b53faee9c5c4a4b742ce7f693a580c9dc7ec0962/src/reader.rs#L1117-L1118

**Comment by pjsier** [comment]
Thanks for the report! It looks like this should have been fixed through the update to string handling here but was missed

https://github.com/georust/kml/blob/b53faee9c5c4a4b742ce7f693a580c9dc7ec0962/src/reader.rs#L1013-L1018

I think handling it similarly with forced decoding is the most straightforward approach. PRs welcome!

**Comment by pjsier** [comment]
@TilBlechschmidt thanks again for reporting this! Are you still interested in creating a PR? No worries if not, just wanted to check if I should put something in

**Comment by TilBlechschmidt** [comment]
Hey @pjsier, sorry for the late reply. I am still interested but not quite sure when I'll get to it (could be a couple of weeks). So if anyone else would be interested in tackling this in the meantime feel free to do so! 🙂
