### ISSUE TITLE
Add support for `Normal` `ColorMode`

### ISSUE THREAD

**Issue by LafeWessel** [georust/kml#56]
When attempting to deserialize a KML that has a `colorMode` set to `normal`, I get an error saying `Invalid color mode: normal`. According to the [spec](https://docs.ogc.org/is/12-007r2/12-007r2.html#879) that the [documentation](https://docs.rs/kml/latest/kml/types/enum.ColorMode.html) cites, the default value for this field is "normal". Thus, the value of "normal" should be deserializable, and I would argue that instead of setting the `colorMode` to "default", it should be "normal" when serializing KMLs.

**Comment by pjsier** [comment]
Thanks for catching this! Looks like I missed this on the initial implementation. If you’re interested in submitting a PR feel free, otherwise I should be able to take a look next week
